import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb786",
        "inverse-surface": "#2f3132",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#00201c",
        "surface-bright": "#f9f9fb",
        "primary": "#000666",
        "surface-container": "#eeeef0",
        "secondary-container": "#8df5e4",
        "primary-fixed-dim": "#bdc2ff",
        "on-tertiary-container": "#ec7700",
        "tertiary-fixed": "#ffdcc6",
        "on-error": "#ffffff",
        "tertiary": "#301300",
        "error-container": "#ffdad6",
        "surface": "#f9f9fb",
        "on-primary": "#ffffff",
        "surface-dim": "#d9dadc",
        "surface-container-highest": "#e2e2e4",
        "tertiary-container": "#4f2400",
        "on-surface": "#1a1c1d",
        "on-surface-variant": "#454652",
        "surface-container-high": "#e8e8ea",
        "inverse-primary": "#bdc2ff",
        "background": "#f9f9fb",
        "primary-container": "#1a237e",
        "inverse-on-surface": "#f0f0f2",
        "error": "#ba1a1a",
        "surface-variant": "#e2e2e4",
        "surface-container-low": "#f3f3f5",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005048",
        "outline-variant": "#c6c5d4",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#000767",
        "secondary": "#006b5f",
        "on-secondary-container": "#007165",
        "surface-tint": "#4c56af",
        "on-primary-fixed-variant": "#343d96",
        "secondary-fixed-dim": "#70d8c8",
        "on-background": "#1a1c1d",
        "on-secondary": "#ffffff",
        "outline": "#767683",
        "primary-fixed": "#e0e0ff",
        "on-tertiary-fixed-variant": "#723600",
        "secondary-fixed": "#8df5e4",
        "on-primary-container": "#8690ee",
        "on-tertiary-fixed": "#311300",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "2xl": "48px",
        gutter: "16px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        xs: "4px",
        sm: "8px",
        lg: "24px",
        xl: "32px",
        base: "4px",
        md: "16px",
      },
      fontFamily: {
        metadata: ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        h3: ["Lexend"],
        h2: ["Lexend"],
        "label-bold": ["Inter"],
        h1: ["Lexend"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        metadata: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        h3: ["24px", { lineHeight: "32px", fontWeight: "600" }],
        h2: ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-bold": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        h1: ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
} satisfies Config;
